version: "3.9"

services:
  nginx:
    build:
      context: .
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

